window.CHAMPION_EXTRAS = {
  "Aatrox": { role: "Top", tiltRisk: "Strong Early", combo: "Q1 - W - Q2 - E - Q3 - AA" },
  "Ahri": { role: "Mid", tiltRisk: "Balanced", combo: "E - Q - W - R - AA" },
  "Akali": { role: "Mid", tiltRisk: "Scaling", combo: "R1 - E1 - E2 - Q - W - R2" },
  "Akshan": { role: "Mid", tiltRisk: "Strong Early", combo: "Q - E - AA - R" },
  "Alistar": { role: "Support", tiltRisk: "Strong Early", combo: "W - Q - E - AA" },
  "Amumu": { role: "Jungle", tiltRisk: "Balanced", combo: "Q - W - E - R" },
  "Anivia": { role: "Mid", tiltRisk: "Scaling", combo: "Q - R - E - W" },
  "Annie": { role: "Mid", tiltRisk: "Balanced", combo: "Flash - R - Q - W - E" },
  "Aphelios": { role: "ADC", tiltRisk: "Scaling", combo: "Q - W - Q - R" },
  "Ashe": { role: "ADC", tiltRisk: "Strong Early", combo: "W - AA - Q - R" },
  "AurelionSol": { role: "Mid", tiltRisk: "Scaling", combo: "E - Q - W - R" },
  "Azir": { role: "Mid", tiltRisk: "Scaling", combo: "W - Q - E - R" },
  "Bard": { role: "Support", tiltRisk: "Strong Early", combo: "Q - AA" },
  "Belveth": { role: "Jungle", tiltRisk: "Scaling", combo: "W - Q - E - R" },
  "Blitzcrank": { role: "Support", tiltRisk: "Strong Early", combo: "Q - E - R" },
  "Brand": { role: "Support", tiltRisk: "Strong Early", combo: "E - Q - W - R" },
  "Braum": { role: "Support", tiltRisk: "Balanced", combo: "Q - W - R - E" },
  "Briar": { role: "Jungle", tiltRisk: "Strong Early", combo: "W - Q - W - E - R" },
  "Caitlyn": { role: "ADC", tiltRisk: "Strong Early", combo: "E - Q - AA - W" },
  "Camille": { role: "Top", tiltRisk: "Scaling", combo: "E - Q - W - Q - R" },
  "Cassiopeia": { role: "Mid", tiltRisk: "Scaling", combo: "Q - E - E - W - R" },
  "Chogath": { role: "Top", tiltRisk: "Scaling", combo: "Q - W - E - R" },
  "Corki": { role: "Mid", tiltRisk: "Scaling", combo: "Q - E - R - W" },
  "Darius": { role: "Top", tiltRisk: "Strong Early", combo: "E - AA - W - Q - R" },
  "Diana": { role: "Jungle", tiltRisk: "Balanced", combo: "Q - E - W - R - E" },
  "Draven": { role: "ADC", tiltRisk: "Strong Early", combo: "W - AA - E - AA - R" },
  "DrMundo": { role: "Top", tiltRisk: "Scaling", combo: "Q - E - W - R" },
  "Ekko": { role: "Jungle", tiltRisk: "Scaling", combo: "W - E - Q - AA - R" },
  "Elise": { role: "Jungle", tiltRisk: "Strong Early", combo: "E - W - Q - R - Q - W" },
  "Evelynn": { role: "Jungle", tiltRisk: "Scaling", combo: "W - Q - E - R" },
  "Ezreal": { role: "ADC", tiltRisk: "Balanced", combo: "W - E - Q - AA - R" },
  "Fiddlesticks": { role: "Jungle", tiltRisk: "Scaling", combo: "R - Q - E - W" },
  "Fiora": { role: "Top", tiltRisk: "Strong Early", combo: "Q - E - W - R" },
  "Fizz": { role: "Mid", tiltRisk: "Balanced", combo: "R - W - Q - E" },
  "Galio": { role: "Mid", tiltRisk: "Balanced", combo: "E - W - Q" },
  "Gangplank": { role: "Top", tiltRisk: "Scaling", combo: "E - E - Q" },
  "Garen": { role: "Top", tiltRisk: "Balanced", combo: "Q - E - W - R" },
  "Gnar": { role: "Top", tiltRisk: "Balanced", combo: "E - R - W - Q" },
  "Gragas": { role: "Jungle", tiltRisk: "Balanced", combo: "W - E - Q - R" },
  "Graves": { role: "Jungle", tiltRisk: "Strong Early", combo: "W - E - Q - R" },
  "Gwen": { role: "Top", tiltRisk: "Scaling", combo: "E - Q - R" },
  "Hecarim": { role: "Jungle", tiltRisk: "Strong Early", combo: "E - W - Q - R" },
  "Heimerdinger": { role: "Mid", tiltRisk: "Strong Early", combo: "E - W - Q" },
  "Hwei": { role: "Mid", tiltRisk: "Scaling", combo: "QW - EE - R" },
  "Illaoi": { role: "Top", tiltRisk: "Balanced", combo: "E - R - W - Q" },
  "Irelia": { role: "Top", tiltRisk: "Strong Early", combo: "E1 - R - Q - E2 - Q" },
  "Ivern": { role: "Jungle", tiltRisk: "Balanced", combo: "Q - E - W" },
  "Janna": { role: "Support", tiltRisk: "Strong Early", combo: "W - Q - E" },
  "JarvanIV": { role: "Jungle", tiltRisk: "Strong Early", combo: "E - Q - W - R" },
  "Jax": { role: "Top", tiltRisk: "Scaling", combo: "E - Q - W - E" },
  "Jayce": { role: "Top", tiltRisk: "Strong Early", combo: "Q - E - R - Q - W - E" },
  "Jhin": { role: "ADC", tiltRisk: "Strong Early", combo: "W - Q - E - R" },
  "Jinx": { role: "ADC", tiltRisk: "Scaling", combo: "E - W - Q - R" },
  "Kaisa": { role: "ADC", tiltRisk: "Scaling", combo: "W - R - Q - E" },
  "Kalista": { role: "ADC", tiltRisk: "Strong Early", combo: "AA - Q - E" },
  "Karma": { role: "Support", tiltRisk: "Strong Early", combo: "R - Q - E - W" },
  "Karthus": { role: "Jungle", tiltRisk: "Scaling", combo: "W - E - Q - R" },
  "Kassadin": { role: "Mid", tiltRisk: "Scaling", combo: "R - E - W - Q" },
  "Katarina": { role: "Mid", tiltRisk: "Scaling", combo: "E - W - Q - R" },
  "Kayle": { role: "Top", tiltRisk: "Scaling", combo: "Q - E - W - R" },
  "Kayn": { role: "Jungle", tiltRisk: "Scaling", combo: "W - Q - R - E" },
  "Kennen": { role: "Top", tiltRisk: "Balanced", combo: "E - R - W - Q" },
  "Khazix": { role: "Jungle", tiltRisk: "Strong Early", combo: "E - Q - W - R" },
  "Kindred": { role: "Jungle", tiltRisk: "Scaling", combo: "W - Q - E - R" },
  "Kled": { role: "Top", tiltRisk: "Strong Early", combo: "E - Q - W" },
  "KogMaw": { role: "ADC", tiltRisk: "Scaling", combo: "E - W - Q - R" },
  "KSante": { role: "Top", tiltRisk: "Scaling", combo: "Q3 - W - R" },
  "Leblanc": { role: "Mid", tiltRisk: "Strong Early", combo: "W - Q - R - E" },
  "LeeSin": { role: "Jungle", tiltRisk: "Strong Early", combo: "Q1 - Q2 - Ward - W - R" },
  "Leona": { role: "Support", tiltRisk: "Strong Early", combo: "E - Q - W - R" },
  "Lillia": { role: "Jungle", tiltRisk: "Scaling", combo: "E - R - W - Q" },
  "Lissandra": { role: "Mid", tiltRisk: "Balanced", combo: "E - W - R - Q" },
  "Lucian": { role: "ADC", tiltRisk: "Strong Early", combo: "E - AA - Q - AA - W - AA" },
  "Lulu": { role: "Support", tiltRisk: "Strong Early", combo: "E - Q - W - R" },
  "Lux": { role: "Mid", tiltRisk: "Balanced", combo: "Q - E - R - E" },
  "Malphite": { role: "Top", tiltRisk: "Balanced", combo: "R - E - W - Q" },
  "Malzahar": { role: "Mid", tiltRisk: "Scaling", combo: "E - W - Q - R" },
  "Maokai": { role: "Support", tiltRisk: "Balanced", combo: "W - Q - E - R" },
  "MasterYi": { role: "Jungle", tiltRisk: "Scaling", combo: "R - E - Q - W" },
  "Milio": { role: "Support", tiltRisk: "Scaling", combo: "W - E - Q - R" },
  "MissFortune": { role: "ADC", tiltRisk: "Strong Early", combo: "E - W - Q - R" },
  "Mordekaiser": { role: "Top", tiltRisk: "Balanced", combo: "E - Q - W - R" },
  "Morgana": { role: "Support", tiltRisk: "Balanced", combo: "Q - W - R - E" },
  "Naafiri": { role: "Mid", tiltRisk: "Balanced", combo: "W - E - Q - R" },
  "Nami": { role: "Support", tiltRisk: "Strong Early", combo: "E - W - Q - R" },
  "Nasus": { role: "Top", tiltRisk: "Scaling", combo: "W - E - Q - R" },
  "Nautilus": { role: "Support", tiltRisk: "Strong Early", combo: "Q - AA - W - E - R" },
  "Neeko": { role: "Mid", tiltRisk: "Strong Early", combo: "E - Q - R - W" },
  "Nidalee": { role: "Jungle", tiltRisk: "Strong Early", combo: "Q - R - W - E - Q" },
  "Nilah": { role: "ADC", tiltRisk: "Scaling", combo: "E - Q - R - W" },
  "Nocturne": { role: "Jungle", tiltRisk: "Balanced", combo: "R - Q - E - W" },
  "Nunu": { role: "Jungle", tiltRisk: "Strong Early", combo: "W - E - Q - R" },
  "Olaf": { role: "Top", tiltRisk: "Strong Early", combo: "Q - W - E - R" },
  "Orianna": { role: "Mid", tiltRisk: "Balanced", combo: "Q - W - R - E" },
  "Ornn": { role: "Top", tiltRisk: "Scaling", combo: "Q - R1 - E - R2 - W - AA" },
  "Pantheon": { role: "Mid", tiltRisk: "Strong Early", combo: "W - AA - Q - E" },
  "Poppy": { role: "Top", tiltRisk: "Strong Early", combo: "E - Q - W - R" },
  "Pyke": { role: "Support", tiltRisk: "Strong Early", combo: "Q - E - W - R" },
  "Qiyana": { role: "Mid", tiltRisk: "Strong Early", combo: "E - Q - W - Q - R" },
  "Quinn": { role: "Top", tiltRisk: "Strong Early", combo: "E - AA - Q - AA" },
  "Rakan": { role: "Support", tiltRisk: "Balanced", combo: "R - W - Q - E" },
  "Rammus": { role: "Jungle", tiltRisk: "Balanced", combo: "Q - E - W - R" },
  "RekSai": { role: "Jungle", tiltRisk: "Strong Early", combo: "W - Q - E - R" },
  "Rell": { role: "Support", tiltRisk: "Balanced", combo: "W - R - E - Q" },
  "Renata": { role: "Support", tiltRisk: "Scaling", combo: "E - Q - W - R" },
  "Renekton": { role: "Top", tiltRisk: "Strong Early", combo: "E - W - Q - E" },
  "Rengar": { role: "Jungle", tiltRisk: "Strong Early", combo: "R - Q - E - W" },
  "Riven": { role: "Top", tiltRisk: "Strong Early", combo: "E - R1 - Q - W - AA - Q - R2 - Q" },
  "Rumble": { role: "Top", tiltRisk: "Strong Early", combo: "E - W - Q - R" },
  "Ryze": { role: "Mid", tiltRisk: "Scaling", combo: "Q - E - Q - W - Q" },
  "Samira": { role: "ADC", tiltRisk: "Balanced", combo: "AA - Q - W - E - R" },
  "Sejuani": { role: "Jungle", tiltRisk: "Balanced", combo: "Q - W - E - R" },
  "Senna": { role: "Support", tiltRisk: "Scaling", combo: "AA - Q - W - E - R" },
  "Seraphine": { role: "Support", tiltRisk: "Scaling", combo: "E - Q - W - R" },
  "Sett": { role: "Top", tiltRisk: "Strong Early", combo: "E - AA - Q - W - R" },
  "Shaco": { role: "Jungle", tiltRisk: "Strong Early", combo: "Q - W - E - R" },
  "Shen": { role: "Top", tiltRisk: "Strong Early", combo: "E - Q - W - R" },
  "Shyvana": { role: "Jungle", tiltRisk: "Scaling", combo: "R - E - W - Q" },
  "Singed": { role: "Top", tiltRisk: "Balanced", combo: "W - E - Q - R" },
  "Sion": { role: "Top", tiltRisk: "Balanced", combo: "E - Q - W - R" },
  "Sivir": { role: "ADC", tiltRisk: "Scaling", combo: "W - Q - E - R" },
  "Skarner": { role: "Jungle", tiltRisk: "Balanced", combo: "E - W - Q - R" },
  "Smolder": { role: "ADC", tiltRisk: "Scaling", combo: "W - Q - E - R" },
  "Sona": { role: "Support", tiltRisk: "Scaling", combo: "E - W - Q - R" },
  "Soraka": { role: "Support", tiltRisk: "Strong Early", combo: "Q - E - W - R" },
  "Swain": { role: "Mid", tiltRisk: "Balanced", combo: "E - W - Q - R" },
  "Sylas": { role: "Mid", tiltRisk: "Balanced", combo: "E1 - E2 - W - Q - AA" },
  "Syndra": { role: "Mid", tiltRisk: "Scaling", combo: "Q - E - W - R" },
  "TahmKench": { role: "Support", tiltRisk: "Strong Early", combo: "Q - W - E - R" },
  "Taliyah": { role: "Mid", tiltRisk: "Strong Early", combo: "W - E - Q - R" },
  "Talon": { role: "Mid", tiltRisk: "Strong Early", combo: "W - Q - R - AA" },
  "Taric": { role: "Support", tiltRisk: "Balanced", combo: "E - W - Q - R" },
  "Teemo": { role: "Top", tiltRisk: "Strong Early", combo: "AA - Q - AA - W" },
  "Thresh": { role: "Support", tiltRisk: "Strong Early", combo: "Q - E - W - R" },
  "Tristana": { role: "ADC", tiltRisk: "Strong Early", combo: "E - W - Q - R" },
  "Trundle": { role: "Top", tiltRisk: "Strong Early", combo: "W - E - Q - R" },
  "Tryndamere": { role: "Top", tiltRisk: "Strong Early", combo: "E - W - Q - R" },
  "TwistedFate": { role: "Mid", tiltRisk: "Balanced", combo: "W (Gold) - Q - E - R" },
  "Twitch": { role: "ADC", tiltRisk: "Scaling", combo: "Q - W - R - E" },
  "Udyr": { role: "Jungle", tiltRisk: "Strong Early", combo: "E - R - W - Q" },
  "Urgot": { role: "Top", tiltRisk: "Balanced", combo: "E - W - Q - R" },
  "Varus": { role: "ADC", tiltRisk: "Strong Early", combo: "R - E - W - Q" },
  "Vayne": { role: "ADC", tiltRisk: "Scaling", combo: "R - Q - E" },
  "Veigar": { role: "Mid", tiltRisk: "Scaling", combo: "E - W - Q - R" },
  "Velkoz": { role: "Mid", tiltRisk: "Balanced", combo: "Q - E - W - R" },
  "Vex": { role: "Mid", tiltRisk: "Balanced", combo: "R1 - R2 - W - E - Q" },
  "Vi": { role: "Jungle", tiltRisk: "Strong Early", combo: "Q - AA - E - R" },
  "Viego": { role: "Jungle", tiltRisk: "Balanced", combo: "W - AA - Q - AA - R" },
  "Viktor": { role: "Mid", tiltRisk: "Scaling", combo: "E - Q - W - R" },
  "Vladimir": { role: "Mid", tiltRisk: "Scaling", combo: "R - E - W - Q" },
  "Volibear": { role: "Top", tiltRisk: "Strong Early", combo: "Q - E - W - R" },
  "Warwick": { role: "Jungle", tiltRisk: "Strong Early", combo: "W - E - Q - R" },
  "Wukong": { role: "Top", tiltRisk: "Strong Early", combo: "E - Q - W - R" },
  "Xayah": { role: "ADC", tiltRisk: "Balanced", combo: "Q - AA - E - W - R" },
  "Xerath": { role: "Mid", tiltRisk: "Scaling", combo: "E - W - Q - R" },
  "XinZhao": { role: "Jungle", tiltRisk: "Strong Early", combo: "E - W - Q - R" },
  "Yasuo": { role: "Mid", tiltRisk: "Scaling", combo: "E - Q3 - R - W" },
  "Yone": { role: "Mid", tiltRisk: "Scaling", combo: "E - Q3 - R - W" },
  "Yorick": { role: "Top", tiltRisk: "Balanced", combo: "E - W - Q - R" },
  "Yuumi": { role: "Support", tiltRisk: "Scaling", combo: "W - Q - E - R" },
  "Zac": { role: "Jungle", tiltRisk: "Balanced", combo: "E - Q - W - R" },
  "Zed": { role: "Mid", tiltRisk: "Strong Early", combo: "R - W - E - Q - AA" },
  "Zeri": { role: "ADC", tiltRisk: "Scaling", combo: "E - W - Q - R" },
  "Ziggs": { role: "Mid", tiltRisk: "Balanced", combo: "E - W - Q - R" },
  "Zilean": { role: "Support", tiltRisk: "Scaling", combo: "E - Q - W - Q - R" },
  "Zoe": { role: "Mid", tiltRisk: "Strong Early", combo: "E - Q - Q - R" },
  "Zyra": { role: "Support", tiltRisk: "Strong Early", combo: "E - W - Q - R" }
};
